#!/bin/bash

echo "🚀 Pushing to GitHub: mshoe1988/landlordhub"
echo "=============================================="
echo ""
echo "Your code is ready to push!"
echo ""
echo "To push, run one of these:"
echo ""
echo "Option 1: Push with Personal Access Token"
echo "  git push -u origin main"
echo "  (When prompted: Username = mshoe1988, Password = YOUR_TOKEN)"
echo ""
echo "Option 2: Push with SSH (if you have SSH keys set up)"
echo "  git remote set-url origin git@github.com:mshoe1988/landlordhub.git"
echo "  git push -u origin main"
echo ""
echo "Option 3: Use GitHub Desktop or VS Code Git extension"
echo ""
echo "After pushing, Vercel will automatically deploy your changes!"
echo ""
